sudo: false

language: python

python:
  - 3.7

install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - pytest tests --cov=tpu_star

after_success:
  - bash <(curl -s https://codecov.io/bash)